### ISSUE TITLE
Program Crash

### ISSUE THREAD

**Issue by godvader8** [marcin-przywoski/FacebookExportDatePhotoFixer#40]
Hello
Great idea, I've been looking for something like this for a long time. However, when I click start, the program crashes. I tried with every .net version.

**Comment by marcin-przywoski** [comment]
Hello!

Can you tell me in what language have you made the export? Two things may have happened - one is that Facebook changed the location where the program gets the information about the language of the export (which is needed for correct parsing of dates due to the use of different formats in different languages) OR Facebook has changed the structure of HTML file which also could brake few things. I'll make a small export myself and check how it works on the latest data. I'll also add a small TODO in the code for better error handling and display

**Comment by marcin-przywoski** [comment]
I see that the facebook has changed the layout of export again - I'll amend that in the weekend and create a new release

**Comment by marcin-przywoski** [comment]
@godvader8 I've recreated the app and it's working with the current Facebook changes. Please use the files from this repo: https://github.com/marcin-przywoski/Facebook-Export-Viewer

**Comment by godvader8** [comment]
Witaj :)
Nie wiem czy mówisz po polsku więc wyślę w dwóch językach.
Uwielbiam Twoja apke, zaoszczędziła mi mnóstwo czasu, jednak przestała
działać z nową wersją lub coś trzeba zmienić.
Mógłbyś mi pomóc? Bardzo mi zależy.
Wiesza się na html, json niby przetwarza ale pliki nie pojawiają się.
Testowałem, ze starych jsonow ściągniętych pol roku temu smiga.
Pozdrowienia!

Hello :) I don't know if you speak Polish, so I will send it in two
languages. I love your app, it saved me a lot of time, but it stopped
working with the new version or something needs to be changed. Could you
help me? It hangs on html, it processes json, but the files do not appear.
I tested that it works fine with old json files downloaded half a year ago.
Greetings!


niedz., 17 wrz 2023 o 23:35 Marcin Przywóski ***@***.***>
napisał(a):
